FROM        node
MAINTAINER  Spencer Scorcelletti <spencer.scorcelletti@salesforce.com>
ADD         ./team-documentation /code
WORKDIR     /code
RUN         npm install
EXPOSE      3000
CMD         npm start
